# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: custom_events.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'custom_events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63ustom_events.proto\x12\x0bproto_types\x1a\x1fgoogle/protobuf/timestamp.proto\"K\n\x19MetricUtilsInterceptStart\x12.\n\nstarted_at\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"T\n\x1cMetricUtilsInterceptStartMsg\x12\x34\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32&.proto_types.MetricUtilsInterceptStart\"j\n\"MetricUtilsInterceptInvokeOriginal\x12.\n\nstarted_at\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x14\n\x0c\x65lapsed_time\x18\x02 \x01(\x02\"f\n%MetricUtilsInterceptInvokeOriginalMsg\x12=\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32/.proto_types.MetricUtilsInterceptInvokeOriginal\"g\n\x1dMetricUtilsInterceptCompleted\x12\x30\n\x0c\x63ompleted_at\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x14\n\x0c\x65lapsed_time\x18\x02 \x01(\x02\"\\\n MetricUtilsInterceptCompletedMsg\x12\x38\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32*.proto_types.MetricUtilsInterceptCompletedb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'custom_events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_METRICUTILSINTERCEPTSTART']._serialized_start=69
  _globals['_METRICUTILSINTERCEPTSTART']._serialized_end=144
  _globals['_METRICUTILSINTERCEPTSTARTMSG']._serialized_start=146
  _globals['_METRICUTILSINTERCEPTSTARTMSG']._serialized_end=230
  _globals['_METRICUTILSINTERCEPTINVOKEORIGINAL']._serialized_start=232
  _globals['_METRICUTILSINTERCEPTINVOKEORIGINAL']._serialized_end=338
  _globals['_METRICUTILSINTERCEPTINVOKEORIGINALMSG']._serialized_start=340
  _globals['_METRICUTILSINTERCEPTINVOKEORIGINALMSG']._serialized_end=442
  _globals['_METRICUTILSINTERCEPTCOMPLETED']._serialized_start=444
  _globals['_METRICUTILSINTERCEPTCOMPLETED']._serialized_end=547
  _globals['_METRICUTILSINTERCEPTCOMPLETEDMSG']._serialized_start=549
  _globals['_METRICUTILSINTERCEPTCOMPLETEDMSG']._serialized_end=641
# @@protoc_insertion_point(module_scope)
