# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: custom_events.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63ustom_events.proto\x12\x0bproto_types\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa5\x02\n\x13\x43oreEventInfoCustom\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x03 \x01(\t\x12\r\n\x05level\x18\x04 \x01(\t\x12\x15\n\rinvocation_id\x18\x05 \x01(\t\x12\x0b\n\x03pid\x18\x06 \x01(\x05\x12\x0e\n\x06thread\x18\x07 \x01(\t\x12&\n\x02ts\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12:\n\x05\x65xtra\x18\t \x03(\x0b\x32+.proto_types.CoreEventInfoCustom.ExtraEntry\x12\x10\n\x08\x63\x61tegory\x18\n \x01(\t\x1a,\n\nExtraEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"K\n\x19MetricUtilsInterceptStart\x12.\n\nstarted_at\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x84\x01\n\x1cMetricUtilsInterceptStartMsg\x12.\n\x04info\x18\x01 \x01(\x0b\x32 .proto_types.CoreEventInfoCustom\x12\x34\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32&.proto_types.MetricUtilsInterceptStart\"j\n\"MetricUtilsInterceptInvokeOriginal\x12.\n\nstarted_at\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x14\n\x0c\x65lapsed_time\x18\x02 \x01(\x02\"\x96\x01\n%MetricUtilsInterceptInvokeOriginalMsg\x12.\n\x04info\x18\x01 \x01(\x0b\x32 .proto_types.CoreEventInfoCustom\x12=\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32/.proto_types.MetricUtilsInterceptInvokeOriginal\"g\n\x1dMetricUtilsInterceptCompleted\x12\x30\n\x0c\x63ompleted_at\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x14\n\x0c\x65lapsed_time\x18\x02 \x01(\x02\"\x8c\x01\n MetricUtilsInterceptCompletedMsg\x12.\n\x04info\x18\x01 \x01(\x0b\x32 .proto_types.CoreEventInfoCustom\x12\x38\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32*.proto_types.MetricUtilsInterceptCompletedb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'custom_events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COREEVENTINFOCUSTOM_EXTRAENTRY']._loaded_options = None
  _globals['_COREEVENTINFOCUSTOM_EXTRAENTRY']._serialized_options = b'8\001'
  _globals['_COREEVENTINFOCUSTOM']._serialized_start=70
  _globals['_COREEVENTINFOCUSTOM']._serialized_end=363
  _globals['_COREEVENTINFOCUSTOM_EXTRAENTRY']._serialized_start=319
  _globals['_COREEVENTINFOCUSTOM_EXTRAENTRY']._serialized_end=363
  _globals['_METRICUTILSINTERCEPTSTART']._serialized_start=365
  _globals['_METRICUTILSINTERCEPTSTART']._serialized_end=440
  _globals['_METRICUTILSINTERCEPTSTARTMSG']._serialized_start=443
  _globals['_METRICUTILSINTERCEPTSTARTMSG']._serialized_end=575
  _globals['_METRICUTILSINTERCEPTINVOKEORIGINAL']._serialized_start=577
  _globals['_METRICUTILSINTERCEPTINVOKEORIGINAL']._serialized_end=683
  _globals['_METRICUTILSINTERCEPTINVOKEORIGINALMSG']._serialized_start=686
  _globals['_METRICUTILSINTERCEPTINVOKEORIGINALMSG']._serialized_end=836
  _globals['_METRICUTILSINTERCEPTCOMPLETED']._serialized_start=838
  _globals['_METRICUTILSINTERCEPTCOMPLETED']._serialized_end=941
  _globals['_METRICUTILSINTERCEPTCOMPLETEDMSG']._serialized_start=944
  _globals['_METRICUTILSINTERCEPTCOMPLETEDMSG']._serialized_end=1084
# @@protoc_insertion_point(module_scope)
